name: clip-env
channels:
  - defaults
dependencies:
  - anyio=4.2.0=py38haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py38haa95532_0
  - attrs=24.2.0=py38haa95532_0
  - babel=2.11.0=py38haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.3=py38haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli=1.0.9=h827c3e9_9
  - brotli-bin=1.0.9=h827c3e9_9
  - brotli-python=1.0.9=py38hd77b12b_8
  - ca-certificates=2025.9.9=haa95532_0
  - certifi=2024.8.30=py38haa95532_0
  - cffi=1.17.1=py38h827c3e9_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py38haa95532_0
  - comm=0.2.1=py38haa95532_0
  - contourpy=1.0.5=py38h59b6b97_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.6.7=py38hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py38haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fonttools=4.51.0=py38h2bbff1b_0
  - freetype=2.13.3=h0620614_0
  - h11=0.14.0=py38haa95532_0
  - httpcore=1.0.2=py38haa95532_0
  - httpx=0.27.0=py38haa95532_0
  - icu=73.1=h6c2663c_0
  - idna=3.7=py38haa95532_0
  - importlib-metadata=7.0.1=py38haa95532_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.0=py38haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=py38haa95532_0
  - ipython=8.12.2=py38haa95532_0
  - ipywidgets=8.1.2=py38haa95532_0
  - jedi=0.19.1=py38haa95532_0
  - jpeg=9f=ha349fce_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.23.0=py38haa95532_0
  - jsonschema-specifications=2023.7.1=py38haa95532_0
  - jupyter=1.0.0=py38haa95532_9
  - jupyter-lsp=2.2.0=py38haa95532_0
  - jupyter_client=8.6.0=py38haa95532_0
  - jupyter_console=6.6.3=py38haa95532_0
  - jupyter_core=5.7.2=py38haa95532_0
  - jupyter_events=0.10.0=py38haa95532_0
  - jupyter_server=2.14.1=py38haa95532_0
  - jupyter_server_terminals=0.4.4=py38haa95532_1
  - jupyterlab=4.2.5=py38haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py38haa95532_0
  - jupyterlab_widgets=3.0.10=py38haa95532_0
  - kiwisolver=1.4.4=py38hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libclang=14.0.6=default_hb5a9fac_2
  - libclang13=14.0.6=default_h8e68704_2
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libkrb5=1.21.3=h885b0b7_4
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h4a159e6_2
  - libsodium=1.0.20=h83e8143_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib=3.7.2=py38haa95532_0
  - matplotlib-base=3.7.2=py38h4ed8f06_0
  - matplotlib-inline=0.1.6=py38haa95532_0
  - mistune=2.0.4=py38haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.8=py38h2bbff1b_0
  - mkl_random=1.2.4=py38h59b6b97_0
  - nbclient=0.8.0=py38haa95532_0
  - nbconvert=7.16.4=py38haa95532_0
  - nbformat=5.10.4=py38haa95532_0
  - nest-asyncio=1.6.0=py38haa95532_0
  - notebook=7.2.2=py38haa95532_1
  - notebook-shim=0.2.3=py38haa95532_0
  - numpy-base=1.24.3=py38h8a87ada_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - overrides=7.4.0=py38haa95532_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.4.0=py38h827c3e9_0
  - pip=24.2=py38haa95532_0
  - pkgutil-resolve-name=1.3.10=py38haa95532_1
  - platformdirs=3.10.0=py38haa95532_0
  - ply=3.11=py38_0
  - prometheus_client=0.14.1=py38haa95532_0
  - prompt-toolkit=3.0.43=py38haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py38h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py38haa95532_1
  - pyparsing=3.0.9=py38haa95532_0
  - pyqt=5.15.10=py38hd77b12b_0
  - pyqt5-sip=12.13.0=py38h2bbff1b_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.20=h8205438_0
  - python-dateutil=2.9.0post0=py38haa95532_2
  - python-fastjsonschema=2.16.2=py38haa95532_0
  - python-json-logger=2.0.7=py38haa95532_0
  - pywin32=305=py38h2bbff1b_0
  - pywinpty=2.0.10=py38h5da7b33_0
  - pyyaml=6.0.2=py38h827c3e9_0
  - pyzmq=25.1.2=py38hd77b12b_0
  - qt-main=5.15.2=h19c9488_12
  - qtconsole=5.6.0=py38haa95532_0
  - qtpy=2.4.1=py38haa95532_0
  - referencing=0.30.2=py38haa95532_0
  - requests=2.32.3=py38haa95532_0
  - rfc3339-validator=0.1.4=py38haa95532_0
  - rfc3986-validator=0.1.1=py38haa95532_0
  - rpds-py=0.10.6=py38h062c2fa_0
  - send2trash=1.8.2=py38haa95532_0
  - setuptools=75.1.0=py38haa95532_0
  - sip=6.7.12=py38hd77b12b_0
  - sniffio=1.3.0=py38haa95532_0
  - soupsieve=2.5=py38haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=h59b6b97_0
  - terminado=0.17.1=py38haa95532_0
  - tinycss2=1.2.1=py38haa95532_0
  - tomli=2.0.1=py38haa95532_0
  - tornado=6.4.1=py38h827c3e9_0
  - traitlets=5.14.3=py38haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=15.1.0=py38h2bbff1b_0
  - urllib3=2.2.3=py38haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - webencodings=0.5.1=py38_1
  - websocket-client=1.8.0=py38haa95532_0
  - wheel=0.44.0=py38haa95532_0
  - widgetsnbextension=4.0.10=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - winpty=0.4.3=4
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zipp=3.20.2=py38haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - cachetools==5.5.2
      - click==8.1.8
      - clip==1.0
      - datasets==3.1.0
      - dill==0.3.8
      - eval-type-backport==0.2.2
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - ftfy==6.2.3
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.41.1
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - huggingface-hub==0.35.3
      - jinja2==3.1.6
      - joblib==1.4.2
      - markdown==3.7
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.1
      - numpy==1.24.4
      - oauthlib==3.3.1
      - packaging==25.0
      - pandas==2.0.3
      - propcache==0.2.0
      - protobuf==5.29.5
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pytz==2025.2
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentry-sdk==2.42.0
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - torch==2.4.1+cu121
      - torchaudio==2.4.1+cu121
      - torchvision==0.19.1+cu121
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - wandb==0.22.2
      - wcwidth==0.2.14
      - werkzeug==3.0.6
      - xxhash==3.6.0
      - yarl==1.15.2
prefix: C:\Users\madhavt2\AppData\Local\miniconda3\envs\clip-env
