name: clip-env-windows
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<3.13
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pillow
  - jupyterlab
  - notebook
  - ipykernel
  - ipywidgets
  - pytorch
  - torchvision
  - pytorch-cuda
  - ffmpeg
  - git
  - ninja
  - psutil
  - requests
  - pip:
      - git+https://github.com/openai/CLIP.git
      - transformers
      - datasets
      - huggingface-hub
      - accelerate
      - pyarrow
      - protobuf
      - tensorboard
      - tensorboard-data-server
      - wandb
      - ftfy
      - regex
      - tqdm
      - google-auth
      - google-auth-oauthlib
      - requests-oauthlib
      - aiohttp
      - aiohappyeyeballs
      - aiosignal
      - async-timeout
      - frozenlist
      - multiprocess
      - propcache
      - sentencepiece
      - safetensors
      - seaborn
      - asgiref
      - black
      - click
      - colorama
      - coverage
      - Django
      - djangorestframework
      - iniconfig
      - isort
      - mypy_extensions
      - packaging
      - pathspec
      - pillow
      - platformdirs
      - pluggy
      - Pygments
      - pytest
      - pytest-cov
      - pytest-django
      - pytest-mock
      - python-decouple
      - pytokens
      - sqlparse
      - tzdata
